name: "CONVERSSIONAL AI BUS BOOKING SYSTEM"
on:
  push:
    branches: ["main"]
env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
  LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
  LANGCHAIN_TRACING_V2: true
  LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
  DATABASE_USER: ${{secrets.DATABASE_USER}}
  DATABASE_NAME: ${{secrets.DATABASE_NAME}}
  DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  DATABASE_HOST: ${{secrets.DATABASE_HOST}}
  DATABASE_PORT: ${{secrets.DATABASE_PORT}}
  JWT_AUTH_SECRET_KEY: ${{secrets.JWT_AUTH_SECRET_KEY}}
  ALGORITHM: "HS256"
  IMAGE_TAG: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker compose -f docker-compose-bbs-python-be.yml up
          docker compose -f docker-compose-bbs-python-be.yml push
      - name: SCP to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          source: "docker-compose-bbs-python-be.yml"
          target: "~/AI_Aritra_BBS/docker-compose-bbs-python-be.yml"

      - name: SSH to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            cd ~/AI_Aritra_BBS
            sudo docker compose down -f docker-compose-bbs-python-be.yml --volumes
            sudo docker compose pull -f docker-compose-bbs-python-be.yml
            sudo docker compose up -f docker-compose-bbs-python-be.yml -d
